"""Shared domain contracts used across fpg-core features."""

from .buildable_space import (
    BuildableLand,
    BuildableSpaceErrorCode,
    BuildableSpaceReferenceData,
    BuildableSpaceRequestData,
    BuildableSpaceResult,
    BuildableSpaceStage,
    EdgeClassification,
    EdgeSetback,
    FloorWidthAlignment,
    LandEdge,
    LandSide,
    NormalizedLand,
    RoadAttachment,
    RoadRole,
    RoadType,
    SetbackCalculationMode,
    SetbackProfile,
    UsableLand,
    UsableLandConstraints,
    ValidationLimits,
)
from .candidate import CandidatePoint
from .candidate_grid import CandidateMap, ResolvedCandidateGrid
from .circulation import (
    CirculationGrid,
    CirculationGridNode,
    CirculationRouteRule,
    CirculationTrafficClass,
    DestinationSelection,
    GridRoutingCostProfile,
    HallwayClassification,
    HallwayTrafficClass,
    RouteCostBreakdown,
)
from .execution import ExecutionMetadata, ExecutionMode, FeatureExecution
from .floor_plan import (
    FloorPlan,
    FloorPlanOpening,
    FloorPlanRoom,
    OpeningId,
    OpeningPurpose,
    OpeningType,
    RoomMetadata,
    RoomRole,
)
from .floor_plan_spec import (
    ConstraintStrength,
    FloorPlanGenerationSpec,
    FloorSpec,
    MatchPolicy,
    RoomId,
    RoomRelationSpec,
    RoomSizeSpec,
    RoomSpec,
    RoomType,
    RoomWidthAxis,
)
from .geometry import Point, Polygon, Segment

__all__ = [
    "BuildableLand",
    "BuildableSpaceErrorCode",
    "BuildableSpaceReferenceData",
    "BuildableSpaceRequestData",
    "BuildableSpaceResult",
    "BuildableSpaceStage",
    "CandidateMap",
    "CandidatePoint",
    "CirculationGrid",
    "CirculationGridNode",
    "CirculationRouteRule",
    "CirculationTrafficClass",
    "ConstraintStrength",
    "DestinationSelection",
    "EdgeClassification",
    "EdgeSetback",
    "ExecutionMetadata",
    "ExecutionMode",
    "FeatureExecution",
    "FloorPlan",
    "FloorPlanGenerationSpec",
    "FloorPlanOpening",
    "FloorPlanRoom",
    "FloorSpec",
    "FloorWidthAlignment",
    "GridRoutingCostProfile",
    "HallwayClassification",
    "HallwayTrafficClass",
    "LandEdge",
    "LandSide",
    "MatchPolicy",
    "NormalizedLand",
    "OpeningId",
    "OpeningPurpose",
    "OpeningType",
    "Point",
    "Polygon",
    "RoadAttachment",
    "RoadRole",
    "ResolvedCandidateGrid",
    "RoadType",
    "RoomId",
    "RoomMetadata",
    "RoomRelationSpec",
    "RoomRole",
    "RoomSizeSpec",
    "RoomSpec",
    "RoomType",
    "RoomWidthAxis",
    "RouteCostBreakdown",
    "Segment",
    "SetbackCalculationMode",
    "SetbackProfile",
    "UsableLand",
    "UsableLandConstraints",
    "ValidationLimits",
]
